# Generated by Django 2.2 on 2020-08-04 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20200804_1508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='name',
            new_name='new',
        ),
    ]
