# Generated by Django 2.2 on 2020-08-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20200804_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=15, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='task_type',
            name='name',
            field=models.CharField(max_length=15, verbose_name='Тип'),
        ),
    ]
