# Generated by Django 2.2 on 2020-08-04 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20200804_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='type_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='type', to='webapp.Task_type', verbose_name='Тип'),
        ),
    ]
