# Generated by Django 2.2 on 2020-08-10 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20200804_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='type_task',
            new_name='type_task_old',
        ),
    ]
