# Generated by Django 2.2 on 2020-08-10 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20200810_0701'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='type_task',
            field=models.ManyToManyField(related_name='type', to='webapp.Task_type', verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='task',
            name='type_task_old',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='type_old', to='webapp.Task_type', verbose_name='Тип'),
        ),
    ]
