# Generated by Django 2.2 on 2020-08-10 07:08

from django.db import migrations


def transfer_tags(apps, schema_editor):
    Task = apps.get_model('webapp.Task')
    for task in Task.objects.all():
        task.type_task.add(task.type_task_old)


def rollback_transfer(apps, schema_editor):
    Task = apps.get_model('webapp.Task')
    for task in Task.objects.all():
        task.type_task_old.set(task.type_task.all())


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20200810_0706'),
    ]

    operations = [
        migrations.RunPython(transfer_tags, rollback_transfer)
    ]