# Generated by Django 2.2 on 2020-08-10 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_auto_20200810_0708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='type_task_old',
        ),
    ]
