# Generated by Django 2.2 on 2020-08-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_auto_20200821_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='project_pk',
            field=models.ManyToManyField(related_name='project', to='webapp.Project', verbose_name='Проект'),
        ),
    ]
