# Generated by Django 2.2 on 2020-08-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_auto_20200821_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='project_pk_new',
            field=models.ManyToManyField(related_name='project', to='webapp.Project', verbose_name='Проект'),
        ),
        migrations.AlterField(
            model_name='task',
            name='project_pk',
            field=models.ManyToManyField(related_name='project_old', to='webapp.Project', verbose_name='Проект_old'),
        ),
    ]
