# Generated by Django 2.2 on 2020-08-21 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_auto_20200821_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='project_pk_new',
        ),
        migrations.RemoveField(
            model_name='task',
            name='project_pk',
        ),
        migrations.AddField(
            model_name='task',
            name='project_pk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='webapp.Project', verbose_name='Проект'),
            preserve_default=False,
        ),
    ]
