# Generated by Django 2.2 on 2020-08-27 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_auto_20200821_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(default='2020-05-10', verbose_name='Дата начала'),
        ),
    ]
